language: rust

rust:
  - stable
  - beta
  - nightly
 
cache: cargo

matrix:
    allow_failures:
        - rust: 
            - beta
            - nightly

before_script: (cargo install rustfmt || true)

script: 
- |
    export PATH=$PATH:~/.cargo/bin &&
    cargo fmt -- --write-mode=diff &&
    cargo build &&
    cargo test

notifications:
    email: false
